In [8]:
import pandas as pd
import numpy as np
import matrix_factorization_utilities

In [9]:
raw_training_dataset_df = pd.read_csv('movie_ratings_data_set_training.csv')
raw_testing_dataset_df = pd.read_csv('movie_ratings_data_set_testing.csv')

FileNotFoundError: File b'movie_ratings_data_set_training.csv' does not exist

In [3]:
movies_ratings.head()

   user_id  movie_id  value
0        1        28      4
1        1        26      4
2        1         9      4
3        1         1      4
4        1        14      4

In [4]:
movies = pd.read_csv("movies.csv",index_col= "movie_id")

In [5]:
movies.head()

                          title                 genre
movie_id
1                 The Sheriff 1  crime drama, western
2          The Big City Judge 1           legal drama
3                 The Sheriff 2  crime drama, western
4         Just a Regular Family               reality
5          The Big City Judge 2           legal drama

In [6]:
# aggregate function is used to take max rating if a user has reviewed a movie twice
ratings_df = pd.pivot_table(movies_ratings,columns="movie_id",values= "value",index= "user_id",aggfunc= np.max)

In [7]:
ratings_df.head()

movie_id,1,2,3,4,5,6,7,8,9,10,...,25,26,27,28,29,30,31,32,33,34
user_id,,,,,,,,,,,,,,,,,,,,,
1,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,...,NaN,4.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN
2,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,4.0
3,4.0,4.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,5.0,NaN,5.0,5.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,...,NaN,NaN,NaN,NaN,3.0,NaN,3.0,2.0,5.0,5.0